# Generated by Django 5.1.9 on 2025-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CalculatorTestModel',
        ),
    ]
